---
- name: download go gzip
  get_url:
    url: "{{ ansible_go_download_url }}"
    dest: \
      /tmp/go.tar.gz
    mode: "u+rwx"
  register: download

- name: extract and move new go folder to /usr/local
  become: true
  # unarchive does not work propertly on macos
  command: tar -C /usr/local -xzf /tmp/go.tar.gz
  args:
    creates: "/usr/local/go"
