---
- name: run uname command and set a fact
  command: uname
  register: ansible_go_uname_result
  changed_when: false

- name: set fact with uname output
  set_fact:
    ansible_go_os: "{{ ansible_go_uname_result.stdout | lower }}"
  changed_when: false

- name: get filename prefix with latest version
  set_fact:
    ansible_go_filename_prefix: \
      "{{ lookup('url', ansible_go_latest_version_url, split_lines=False) }}"
  when: ansible_go_version == "latest"

- name: get filename prefix with fixed version
  set_fact:
    ansible_go_filename_prefix: go{{ ansible_go_version }}
  when: ansible_go_version != "latest"

- name: try to get current go version installed
  command: go version
  register: result
  changed_when: false

- name: set ansible_go_current_version var
  set_fact:
    ansible_go_current_version: "{{ result.stdout.split(' ')[2] }}"
  when: result.failed == false

- name: set ansible_go_current_version var to none
  set_fact:
    ansible_go_current_version: "none"
  when: result.failed == true

- name: Get home directory of example_user
  ansible.builtin.debug:
    msg: "{{ ansible_go_host_user }}"

- include_tasks: ./macos.yml
  when: ansible_go_os == 'darwin'

- include_tasks: ./ubuntu.yml
  when: ansible_go_os == 'linux'
