---
driver:
  name: default
platforms:
  - name: instance
provisioner:
  name: ansible
  config_options:
    defaults:
      ansible_connection: local
verifier:
  name: testinfra
  options:
    s: true
